services:
  - type: web
    name: collab-hub
    env: python
    buildCommand: |
      pip install -r requirements.txt &&
      python reset_db.py
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: collab-hub-db
          property: connectionString