databases:
  - name: colabhubdb
    plan: free
    databaseName: colabhub
    user: colabhub_user

services:
  - type: web
    name: colab-hub
    env: python
    region: frankfurt
    plan: free
    pythonVersion: "3.11.0"
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_APP
        value: app.py
      - key: DATABASE_URL
        fromDatabase:
          name: colabhubdb
          property: connectionString
    healthCheckPath: /health
    autoDeploy: true